### ISSUE TITLE
Feature/ Record api들 전환

### ISSUE THREAD

**Issue by 1000chw** [BookJamm/BE#7]
## 📝 개요
- /records api들 nest로 변환하기 

## ✔️ To-Do
- [ ] entity 생성
- [ ] dto 생성
- [ ] repository 생성
- [ ] module, controller, service 구현
- [ ] api 차근차근 작성

## 👀 ETC
- 참고자료 등 기타 내용 작성

**Comment by eomgerm** [comment]
불필요한 API
